#!/bin/sh
kak -n -e 'source /usr/share/kak/rc/core/diff.kak
       source /home/spowell/.config/kak/plugins/kakoune-termcolor/tc.kak
       source /usr/share/kak/rc/core/doc.kak
       map global normal q :quit<ret>'
