################################
#           plugins            #
################################

# First time setup
# git clone https://codeberg.org/jdugan6240/kak-bundle $HOME/.config/kak/autoload/bundle/kak-bundle
# :bundle-install
# pacman -S luajit

set-option global tabstop       4
set-option global indentwidth   4
set-option global aligntab      false

set-option global bundle_parallel %sh{nproc}

define-command -params 1 bundle-load %{
    source "%opt{bundle_path}/%arg{1}-load.kak"
}

bundle kakoune-cd https://github.com/delapouite/kakoune-cd %{
    alias global cdc change-directory-current-buffer
    alias global pwd  print-working-directory
}

bundle kakoune-source https://github.com/krornus/kakoune-source %{
    source-all ".kakrc"
}

bundle-noload kakoune-toggle-map https://github.com/krornus/kakoune-toggle-map %{
    toggle-map global normal <F3> hlsearch-on hlsearch-off
}

bundle kakoune-hlsearch https://github.com/krornus/kakoune-hlsearch %{
    bundle-load kakoune-toggle-map
}

bundle-noload kakoune-buffers https://github.com/delapouite/kakoune-buffers %{
    map global normal  b ": enter-user-mode buffers<ret>"
}

bundle-noload peneira-filters https://codeberg.org/mbauhardt/peneira-filters %{
    require-module peneira-buffers
}

bundle-noload peneira https://github.com/gustavo-hms/peneira %{
    require-module peneira
    set-option global peneira_files_command "rg --files"

    bundle-load peneira-filters
    bundle-load kakoune-buffers

    map global buffers b ": peneira-buffers<ret>" -docstring "find buffer"
    map global buffers f ": peneira-mru<ret>" -docstring "find file"
}

bundle-noload mru-files 'git clone https://gitlab.com/kstr0k/mru-files.kak.git mru-files' %{
    require-module mru-files
    bundle-load peneira

    set-option global mru_files_max 100
}

bundle luar https://github.com/gustavo-hms/luar %{
    set-option global luar_interpreter luajit
    bundle-load mru-files
}

bundle kakoune-cargo https://gitlab.com/Screwtapello/kakoune-cargo.git %{
    hook global WinSetOption filetype=rust %{
        map -docstring "cargo build" global user m ": cargo build<ret>"
    }
}

################################
#           options            #
################################
colorscheme gruvbox-clear

set-option global jumpclient    client0
set-option global toolsclient   client1
set-option global docsclient    client1

set-option global grepcmd 'rg -Hn'
set-option global ignored_files %sh{git-ignored | paste -sd '|'}
set-option global matching_pairs ( ) { } [ ]

################################
#             maps             #
################################
alias global x    write-quit
alias global W    write
alias global rns  rename-session
alias global rnc  rename-client

map -docstring "comment line" global user c "<esc>: comment-line<ret>"
map -docstring "make" global user m ": make<ret>"
map -docstring "yank" global user y "<a-|> wl-copy<ret>"

# b->q, q->user mode, b->buffers mode
map global normal q b
map global normal Q B
map global normal <a-q> <a-b>
map global normal <a-Q> <a-B>

# old space/comma order
map global normal , <space>
map global normal <space> ,

################################
#           hooks              #
################################
# relative line numbers
hook global WinCreate (?S)^[^*].+[^*]$ %{
    add-highlighter window/relnum number-lines -relative -hlcursor
}

hook global WinCreate .+\.md$ %{
    add-highlighter buffer/wrap wrap -word -indent
}

# tab complete
hook global InsertCompletionShow .* %{ try %{
    execute-keys -draft 'h<a-K>\h<ret>'
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}}

hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}

# escape with jk
hook global InsertChar k %{ try %{
    exec -draft hH<a-k>jk<ret>d
    exec <esc>
}}

require-module vimtab

hook global BufCreate .* %{
    expandtab
}

hook global WinSetOption filetype=makefile %{
    noexpandtab
}

################################
#          highlighters        #
################################
# Highlight trailing spaces
add-highlighter global/matching show-matching
add-highlighter global/trailing regex '\h+$' 0:default,rgb:424242

eval %sh{kak-lsp}
set-option global lsp_snippet_support false

hook -group lsp-filetype-clangd global BufSetOption filetype=(?:c|cpp) %{
    set-option buffer lsp_servers %{
        [clangd]
        args = ["--log=error"]
        root_globs = ["compile_commands.json", ".clangd", ".git", ".hg"]
    }
}

hook -group lsp-filetype-python global BufSetOption filetype=python %{
    set-option buffer lsp_servers %{
        [pyrefly]
        root_globs = ["pyproject.toml", "setup.py", "poetry.lock", ".git", ".hg"]
        command = "pyrefly"
        args = ["lsp"]
    }
}

hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp|gdscript) %{
    lsp-enable-window
    map -docstring "lsp mode" global user l ": enter-user-mode lsp<ret>"
    map -docstring "goto definition" global goto d "<esc>: lsp-definition<ret>"
    map -docstring "goto symbol" global goto s "<esc>: lsp-goto-document-symbol<ret>"
}
