theme = "modern"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 16

[[block]]
block = "music"
player = "spotify"
buttons = ["prev","play","next"]

[[block]]
block = "sound"

[[block]]
block = "net"
device = "wlp58s0"
ip = true
speed_down = false
speed_up = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "battery"
interval = 10
show = "percentage"

[[block]]
block = "pacman"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
