#!/bin/sh
set -e
ROOT=$(git rev-parse --show-toplevel)
git status -z --ignored 	| 
	head -zn 100 		|
	sed -z '/!/!d; s/!! //' |
	tr '\0' '\n' | while read -r line; do
		echo $(realpath --relative-to=$PWD "$ROOT/$line")
done
