#!/usr/bin/env python

import argparse

parser = argparse.ArgumentParser()
parser.add_argument("amount", type=int, help="overlow length")
parser.add_argument("-c", help="char to use")

args = parser.parse_args()

if __name__ == "__main__":
    c = 'a'
    if args.c is not None:
        c = args.c
    

    print(c*args.amount, end="")

